create extension if not exists "uuid-ossp";

create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  monthly_budget numeric(10, 2) default 0.00,
  currency varchar(3) default 'MXN',
  alert_80_sent_month date,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  category_key varchar(50) not null,
  name varchar(50) not null,
  icon_name varchar(50) not null,
  color_hex varchar(7) not null,
  is_default boolean default false,
  created_at timestamptz default timezone('utc', now()),
  unique (user_id, category_key)
);

create table if not exists public.transactions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  category_id bigint references public.categories(id),
  amount numeric(10, 2) not null check (amount > 0),
  description varchar(100),
  transaction_date date not null default current_date,
  payment_method varchar(50),
  created_at timestamptz default timezone('utc', now())
);

create table if not exists public.alerts (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  transaction_id uuid references public.transactions(id) on delete cascade,
  alert_type varchar(40) not null,
  title varchar(120) not null,
  body text not null,
  is_read boolean default false,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists public.recurring_expenses (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  category_id bigint references public.categories(id),
  name varchar(80) not null,
  merchant varchar(80),
  amount numeric(10, 2) not null check (amount > 0),
  billing_day integer not null check (billing_day between 1 and 31),
  is_active boolean default true,
  created_at timestamptz default timezone('utc', now())
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.transactions enable row level security;
alter table public.alerts enable row level security;
alter table public.recurring_expenses enable row level security;

create policy "Profiles are private"
  on public.profiles for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Categories are private"
  on public.categories for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Transactions are private"
  on public.transactions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Alerts are private"
  on public.alerts for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Recurring expenses are private"
  on public.recurring_expenses for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, monthly_budget, currency)
  values (new.id, 12000.00, 'MXN')
  on conflict (id) do nothing;

  insert into public.categories (user_id, category_key, name, icon_name, color_hex, is_default)
  values
    (new.id, 'comida', 'Comida', 'utensils', '#c86f5f', true),
    (new.id, 'hogar', 'Hogar', 'home', '#7d9d8c', true),
    (new.id, 'cafe', 'Cafe', 'coffee', '#d5a83f', true),
    (new.id, 'compras', 'Compras', 'shopping-bag', '#6d99b8', true),
    (new.id, 'servicios', 'Servicios', 'wallet-cards', '#536f55', true)
  on conflict (user_id, category_key) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.enqueue_weekly_max_alert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_week_start date := date_trunc('week', new.transaction_date)::date;
  current_week_end date := current_week_start + interval '6 days';
  prior_max numeric(10, 2);
begin
  select coalesce(max(amount), 0)
  into prior_max
  from public.transactions
  where user_id = new.user_id
    and id <> new.id
    and transaction_date between current_week_start and current_week_end;

  if new.amount > prior_max and prior_max > 0 then
    insert into public.alerts (user_id, transaction_id, alert_type, title, body)
    values (
      new.user_id,
      new.id,
      'weekly_max',
      'Nuevo gasto alto de la semana',
      'Este movimiento es el gasto mas alto que llevas registrado esta semana.'
    );
  end if;

  return new;
end;
$$;

drop trigger if exists transactions_weekly_max_alert on public.transactions;

create trigger transactions_weekly_max_alert
after insert on public.transactions
for each row execute function public.enqueue_weekly_max_alert();

create or replace function public.enqueue_budget_80_alert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  month_start date := date_trunc('month', new.transaction_date)::date;
  monthly_spent numeric(10, 2);
  budget numeric(10, 2);
  already_sent date;
begin
  select monthly_budget, alert_80_sent_month
  into budget, already_sent
  from public.profiles
  where id = new.user_id;

  if budget is null or budget <= 0 then
    return new;
  end if;

  if already_sent = month_start then
    return new;
  end if;

  select coalesce(sum(amount), 0)
  into monthly_spent
  from public.transactions
  where user_id = new.user_id
    and transaction_date >= month_start
    and transaction_date < (month_start + interval '1 month');

  if monthly_spent >= budget * 0.8 then
    insert into public.alerts (user_id, transaction_id, alert_type, title, body)
    values (
      new.user_id,
      new.id,
      'budget_80',
      'Presupuesto en zona sensible',
      'Ya consumiste al menos 80% de tu presupuesto mensual.'
    );

    update public.profiles
    set alert_80_sent_month = month_start
    where id = new.user_id;
  end if;

  return new;
end;
$$;

drop trigger if exists transactions_budget_80_alert on public.transactions;

create trigger transactions_budget_80_alert
after insert on public.transactions
for each row execute function public.enqueue_budget_80_alert();

create or replace view public.monthly_spending as
select
  user_id,
  date_trunc('month', transaction_date)::date as month,
  sum(amount)::numeric(10, 2) as spent
from public.transactions
group by user_id, date_trunc('month', transaction_date)::date;

create or replace view public.monthly_recurring_commitments as
select
  user_id,
  sum(amount)::numeric(10, 2) as committed_amount,
  count(*)::integer as active_count
from public.recurring_expenses
where is_active = true
group by user_id;
